### ISSUE TITLE
Number of ROIs

### ISSUE THREAD

**Issue by e-bug** [uclanlp/visualbert#11]
Hi and thanks for the nice repo!
1. I couldn't find in the paper how many proposals you used for pre-training and fine-tuning in each dataset (except for NLVR, where you use 144).
2. Also, could it be that you do the "Task-Agnostic Pre-Training" on COCO separately for each task? (Given that you use different detectors for each task)

Thanks a lot! And congrats on the ACL follow-up paper

**Comment by liunian-harold-li** [comment]
Hi, thank you for your interest!

1. We follow past conventions when preparing the image features for each task.
    For VQA, we follow Pythia 1.0 and use 100 boxes per image.
    For VCR, we follow R2C (the model shipped with the paper) and use provided boxes.
    For Flickr30K, we follow BAN (https://arxiv.org/pdf/1805.07932.pdf <https://arxiv.org/pdf/1805.07932.pdf>) and use 10-100 boxes with a confidence threshold.

2. Yes. We did this because we wanted to follow past conventions for each task and these tasks each extract image features differently. So we have to pre-train on COCO with several sets of image features. For example, for pre-training on COCO for the VQA task, we use Pythia 1.0’s detector and use 100 boxes per COCO image. For pre-training on COCO for Flickr30K, we use BAN’s way (which is BUTD features) and use 10-100 boxes per COCO image.

Hope that answers your question!
